[tox]
requires =
    tox>=4
env_list = sqlalchemy20

[testenv]
deps =
  pytest>=7.4.2,<8.0.0
  clickhouse-sqlalchemy>=0.3.2,<0.4.0
  sqlalchemy20: SQLAlchemy>=2.0.0,<2.1.0
commands =
  pytest {posargs: .}
